### ISSUE TITLE
Ошибка в описании "Пример 2. Система 4 уравнений"

### ISSUE THREAD

**Issue by AndreyL7** [Coursera-machine-learning-data-analysis/1#3]
Пример 2. Система 4 уравнений
Рассмотрим простую систему из 2 линейных уравнений с 2 неизвестными:
A + C = 2 (4)
-A + B - 2C + D = -2 (5)
4A + C - 2D = 0 (6)
-4A + 4B + D = 5 (7)
---- здесь речь о 4 уравнениях с 4 незвестными. Так ведь?

**Comment by lexnekr** [comment]
Да, опечатался.

Кстати, есть интерактивный практикум на эту тему - https://stepik.org/lesson/31653/step/1
